main: com.Thebatz.Walls.Main
api-version: 1.13
version: 1.0
name: Walls
author: Thebatz
description: Walls mini-game
depend: [WorldEdit]
commands:
  walls:
    description: Type '/walls help' for more info